package emit

import (
	_ "embed"
	"fmt"
	"strings"
)

// playSrc is the windowed harness. It is a file rather than a string in this
// one because it is full of per cent signs that a format string would have to
// escape, and a template with two named holes is easier to read and to get
// right than one with sixty.
//
//go:embed harness/play.go.txt
var playSrc string

// mainProgram writes the harness: the program that boots the cartridge and
// runs it.
//
// It is headless for now -- it boots, steps frames and can print the name
// table -- because the Ebiten window, the keyboard matrix and the sound mixer
// are M4 and there is no point pretending otherwise. What it does prove is
// that the generated module compiles and that the translated code runs.
func (m Module) mainProgram() error {
	src := fmt.Sprintf(`// Code generated by msx2go. DO NOT EDIT.

// Command %[1]s runs the translated cartridge.
//
// Built with -tags msxdata the cartridge's data is compiled in and this needs
// nothing beside it. Without that tag it looks for %[1]s.dat; -extract writes
// that file back out from a build that has it.
//
// It is headless. The window, the keyboard and the sound belong in a harness
// that knows what it is showing; what this proves is that the translated code
// boots and runs, and -digest is how it is compared against another machine
// running the same cartridge.
package main

import (
	"crypto/sha1"
	"encoding/hex"
	"flag"
	"fmt"
	gopng "image/png"
	"os"
	"strings"

	"%[2]s/z80"
)

func main() {
	data := flag.String("data", "", "where to find %[1]s.dat")
	extract := flag.String("extract", "", "write the cartridge data here and stop")
	frames := flag.Int("frames", 60, "how many frames to run")
	tape := flag.String("tape", "", "replay a recorded tape: one byte of "+
		"button state per frame")
	digest := flag.Int("digest", 0, "print a digest of VRAM, RAM and the "+
		"sound registers every this many frames")
	ramdump := flag.String("ramdump", "", "write RAM from C000h out here at the end")
	cycles := flag.Bool("cycles", false, "print the T-states counted at the end")
	cpu := flag.Float64("cpu", 1, "processor speed as a multiple of a stock "+
		"MSX; negative turns cycle accounting off entirely")
	learn := flag.String("learn", "", "write every address that had to run "+
		"interpreted here, in the form msx2go -sites reads. Append it to "+
		"the module's sites.txt and regenerate, and those addresses are "+
		"translated code in the next build")
	savestate := flag.String("savestate", "", "write a snapshot here at the end")
	loadstate := flag.String("loadstate", "", "start from this snapshot rather "+
		"than booting")
	screen := flag.Bool("screen", false, "print the name table as text at the end")
	png := flag.String("png", "", "write the last frame here as a PNG")
	vramspan := flag.String("vramspan", "", "from:to:file -- append VRAM and "+
		"the VDP registers for every frame in [from,to] to file, for "+
		"comparing against a reference machine")
	stoponmiss := flag.Bool("stoponmiss", false, "stop as soon as a frame "+
		"reaches an address with no label (discovery builds only): from "+
		"the first miss on the machine runs on fake returns, so nothing "+
		"after it is worth the time")
	flag.Parse()

	if *extract != "" {
		out, err := z80.Cartridge.Extract(*extract)
		if err != nil {
			die(err)
		}
		fmt.Println("wrote", out)
		return
	}

	m, err := z80.Cartridge.Open(*data)
	if err != nil {
		die(err)
	}
	var buttons []byte
	if *tape != "" {
		if buttons, err = os.ReadFile(*tape); err != nil {
			die(err)
		}
	}
	m.CPUScale = *cpu
	m.LearnSites = *learn != ""
	// A snapshot is a machine that has already booted; booting it again
	// would run INIT over a running game. See runtime/snapshot.go.
	if *loadstate != "" {
		f, err := os.Open(*loadstate)
		if err != nil {
			die(err)
		}
		if err := m.LoadState(f, z80.Cartridge.SHA1); err != nil {
			die(err)
		}
		f.Close()
	} else if err := z80.Cartridge.Start(m, z80.Base); err != nil {
		die(err)
	}
	var spanFrom, spanTo int
	var spanFile *os.File
	if *vramspan != "" {
		var name string
		if _, err := fmt.Sscanf(*vramspan, "%%d:%%d:", &spanFrom, &spanTo); err != nil {
			die(err)
		}
		if i := strings.LastIndex(*vramspan, ":"); i >= 0 {
			name = (*vramspan)[i+1:]
		}
		if spanFile, err = os.Create(name); err != nil {
			die(err)
		}
		defer spanFile.Close()
	}
	for i := 0; i < *frames; i++ {
		// What the window does: one press reaches a cartridge through
		// the joystick port and through the keyboard matrix, and a
		// cartridge is entitled to read either. Driving only the
		// matrix here made this program disagree with the window it
		// is supposed to reproduce, which is worse than useless when
		// it is being used to chase a disagreement.
		if i < len(buttons) {
			b := z80.Buttons(buttons[i])
			m.SetJoystick(b)
			m.SetInput(b)
		} else if buttons != nil {
			m.SetJoystick(0)
			m.SetInput(0)
		}
		if err := m.Frame(); err != nil {
			die(err)
		}
		if spanFile != nil && i+1 >= spanFrom && i+1 <= spanTo {
			spanFile.Write(m.VDP.VRAM[:])
			spanFile.Write(m.VDP.Reg[:])
		}
		if *stoponmiss && len(m.Discovered()) > 0 {
			break
		}
		if *digest > 0 && (i+1)%%*digest == 0 {
			fmt.Printf("%%d vram %%s ram %%s psg %%s\n",
				i+1, h(m.VDP.VRAM[:]), h(m.Mem[0xC000:]),
				h(m.PSG.Reg[:]))
		}
	}
	if *ramdump != "" {
		os.WriteFile(*ramdump, m.Mem[0xC000:], 0o644)
	}
	if *cycles {
		fmt.Printf("cycles %%d\n", m.Cyc)
	}
	if *learn != "" {
		var b strings.Builder
		b.WriteString("# Addresses this build had to interpret, with the " +
			"banks in force.\n")
		b.WriteString("# Append to sites.txt and regenerate: interpreted " +
			"this time, translated next time.\n")
		for _, l := range m.Learned() {
			b.WriteString(l)
			b.WriteByte('\n')
		}
		if err := os.WriteFile(*learn, []byte(b.String()), 0o644); err != nil {
			die(err)
		}
		fmt.Fprintf(os.Stderr, "%%s: %%d interpreted site(s) -> %%s\n",
			z80.Cartridge.Name, len(m.Learned()), *learn)
	}
	if *savestate != "" {
		f, err := os.Create(*savestate)
		if err != nil {
			die(err)
		}
		if err := m.SaveState(f, z80.Cartridge.SHA1); err != nil {
			die(err)
		}
		if err := f.Close(); err != nil {
			die(err)
		}
	}
	// A discovery build collects the addresses it could not reach instead
	// of stopping at the first. They go to stderr in the form
	// msx2go -discover reads back.
	for _, d := range m.Discovered() {
		fmt.Fprintf(os.Stderr, "MSX2GO-NOLABEL %%s\n", d)
	}
	if *digest == 0 {
		fmt.Printf("%%s: %%d frames\n", z80.Cartridge.Name, m.Frames())
	}
	if *screen {
		fmt.Print(z80.ScreenText(m))
	}
	if *png != "" {
		f, err := os.Create(*png)
		if err != nil {
			die(err)
		}
		img := z80.NewRenderer().RenderVDP(&m.VDP)
		if err := gopng.Encode(f, img); err != nil {
			die(err)
		}
		f.Close()
	}
}

// h hashes one region. The three are kept apart because "they differ" is not
// a lead and "the RAM differs and the video does not" is.
func h(b []byte) string {
	sum := sha1.Sum(b)
	return hex.EncodeToString(sum[:])[:12]
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "%[1]s:", err)
	os.Exit(1)
}
`, m.Info.Name, m.ModPath)
	if err := m.put("cmd/"+m.Info.Name+"/main.go", []byte(src)); err != nil {
		return err
	}
	return m.playProgram()
}

// playProgram writes the windowed harness, on Ebiten so that the same source
// builds for a desktop and for a browser.
//
// It is a second binary rather than a flag on the first because the headless
// one has no dependencies at all -- it builds and runs anywhere, which is what
// makes it useful for comparing two machines -- and this one needs a graphics
// library fetched from the network.
func (m Module) playProgram() error {
	src := strings.NewReplacer(
		"__NAME__", m.Info.Name,
		"__MODULE__", m.ModPath,
		"**SCALE**", "**scale",
	).Replace(playSrc)
	return m.put("cmd/"+m.Info.Name+"-play/main.go", []byte(src))
}
